language: python
python:
  - "2.7"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

install:
  - pip install ansible

script:
  - ansible-playbook tests/test.yml --syntax-check
