---
- name: Install autossh
  package: name=autossh state=latest
  become: yes
  notify: Restart service
- name: Create user with {{ autossh_name }} key
  user:
    name: autossh
    shell: /sbin/nologin
    generate_ssh_key: yes
    ssh_key_file: .ssh/{{ autossh_name }}
  become: yes
  register: create_user_result
- name: Export public key for {{ autossh_name }}
  set_fact:
    autossh_public_keys: >-
      {{
      autossh_public_keys |
      default({}) |
      combine({autossh_name: create_user_result.ssh_public_key})
      }}
- name: Add {{ autossh_name }} host key
  known_hosts:
    name: "[{{ autossh_host }}]:{{ autossh_port }}"
    key: "{{ autossh_hostkey }}"
  become: true
  become_user: autossh
- name: Copy initscript
  copy:
    src: initscript.sh
    dest: /etc/init.d/autossh
    mode: 0755
  become: yes
  notify: Restart service
- name: Configure {{ autossh_name }} service
  template:
    src: configuration.j2
    dest: /etc/conf.d/autossh.{{ autossh_name }}
  become: yes
  notify: Restart service
- name: Link to {{ autossh_name }} initscript
  file:
    state: link
    path: /etc/init.d/autossh.{{ autossh_name }}
    src: /etc/init.d/autossh
  become: yes
- name: Start {{ autossh_name }} service
  service: name=autossh.{{ autossh_name }} enabled=yes state=started
  become: yes
