---
- name: Install autossh
  package: name=autossh state=latest
  become: yes
  notify: Restart services
- name: Create user
  user: name=autossh shell=/sbin/nologin
  become: yes
- name: Copy initscript
  copy:
    src: initscript.sh
    dest: /etc/init.d/autossh
    mode: 0755
  become: yes
  notify: Restart services
- name: Configure services
  template:
    src: configuration.j2
    dest: /etc/conf.d/autossh.{{ autossh_name }}
  become: yes
  notify: Restart services
- name: Link to initscript
  file:
    state: link
    path: /etc/init.d/autossh.{{ autossh_name }}
    src: /etc/init.d/autossh
  become: yes
- name: Start services
  service: name=autossh.{{ autossh_name }} enabled=yes state=started
  become: yes
