---
- name: Install autossh
  package: name=autossh state=latest
  become: yes
- name: Create user
  user: name=autossh shell=/sbin/nologin
  become: yes
- name: Copy initscript
  copy:
    src: initscript.sh
    dest: /etc/init.d/autossh
    mode: 0755
  become: yes
- name: Configure
  template:
    src: configuration.j2
    dest: /etc/conf.d/autossh.{{ item.key }}
  with_dict: "{{ targets }}"
  become: yes
- name: Link to scripts
  file:
    state: link
    path: /etc/init.d/autossh.{{ item.key }}
    src: /etc/init.d/autossh
  with_dict: "{{ targets }}"
  become: yes
- name: Start services
  service: name=autossh.{{ item.key }} enabled=yes state=started
  with_dict: "{{ targets }}"
  become: yes
